---
title: "Fear Acquisition"
author: "Vera Bouwman"
date: "2/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, include=FALSE,echo=FALSE}
library(here)
library(ggplot2)
library(tidyverse)
library(car)
library(broom)
library(knitr)
```

## Introduction

ANOVAs are performed to compare the three CSs (CS1, CS2, CS3) on the first en last trial on expectancy and fear outcome. We expect the three CSsen to be similar at the first trial. At the last trial, we expect the CS1 to be high and the CS2 en CS3 to be low.

## Analyses

```{r load data}
acquisition_expectancy <- read.csv("data/processed/acquisition_expectancy.csv")
acquisition_fear <- read.csv("data/processed/acquisition_fear.csv")
```

```{r analyses for expectancy}

# Make long format
expectancy_long <- acquisition_expectancy %>% 
  pivot_longer(contains("verwachting"), names_to = "CS", values_to = "response") %>% 
  separate(CS, into = c("acq", "exp", "CS", "trial")) %>% 
  select(c(-acq,-exp))

# ANOVA to compare CSsen on first trial
first_trial_expectancy <- expectancy_long %>% 
  filter(trial == 1)

ANOVA_first_expectancy <- lm(response ~ CS, first_trial_expectancy) %>% 
  Anova(type = 3) %>% 
  tidy()

kable(ANOVA_first_expectancy, caption = "ANOVA of first expectancy trial", digits = 3)

# ANOVA to compare CSsen on last trial
last_trial_expectancy <- expectancy_long %>% 
  filter(trial == 6)

ANOVA_last_expectancy <- lm(response ~ CS, last_trial_expectancy) %>% 
  Anova(type = 3) %>% 
  tidy()

kable(ANOVA_last_expectancy, caption = "ANOVA of last expectancy trial", digits = 3)
```

```{r analyses for fear}

# Make long format
fear_long <- acquisition_fear %>% 
  pivot_longer(contains("angst"), names_to = "CS", values_to = "response") %>% 
  separate(CS, into = c("acq", "fear", "CS", "trial")) %>% 
  select(c(-acq,-fear)) 

# ANOVA to compare CSsen on first trial
first_trial_fear <- fear_long %>% 
  filter(trial == 1)

ANOVA_first_fear <- lm(response ~ CS, first_trial_fear) %>% 
  Anova(type = 3) %>% 
  tidy()

kable(ANOVA_first_fear, caption = "ANOVA of first fear trial", digits = 3)

# ANOVA to compare CSsen on last trial
last_trial_fear <- fear_long %>% 
  filter(trial == 6)

ANOVA_last_fear<- lm(response ~ CS, last_trial_fear) %>% 
  Anova(type = 3) %>% 
  tidy()

kable(ANOVA_last_fear, caption = "ANOVA of last fear trial", digits = 3)
```

## Plots

```{r last CS trials}
#Expectancy
plot_last_exp <- last_trial_expectancy %>% 
  group_by(CS) %>% 
  summarise(response = mean(response)) 

ggplot(plot_last_exp, aes(CS, response)) +
  geom_col() +
  theme_classic() +
  labs(caption = "Last expectancy trial", y = "Expectancy")

ggsave(here("./results/figures/plot_last_expectancy.png"), width = 10, height = 5) 

#Fear
plot_last_fear <- last_trial_fear %>% 
  group_by(CS) %>% 
  summarise(response = mean(response)) 

ggplot(plot_last_fear, aes(CS, response)) +
  geom_col() +
  theme_classic() +
  labs(caption = "Last fear trial", y = "Fear") +
  ylim(0,50)
  
ggsave(here("./results/figures/plot_last_fear.png"), width = 10, height = 5) 

```
